# Generated by Django 4.2.7 on 2026-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_safetyzone_sosalert_customuser_home_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='media_evidence',
            field=models.FileField(blank=True, null=True, upload_to='sos_evidence/'),
        ),
    ]
