# Generated by Django 4.2.7 on 2026-04-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_communityreport_latitude_communityreport_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High danger')], default='medium', max_length=15),
        ),
    ]
