# Generated by Django 4.2.7 on 2026-04-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_dangerzone_locationhistory_sosalert_alert_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosalert',
            name='media_evidence',
        ),
        migrations.AddField(
            model_name='sosalert',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='sos/audio/'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sos/images/'),
        ),
    ]
