# Generated by Django 4.2.7 on 2026-04-07 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_locationhistory_sos_alert_trackingsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingsession',
            name='token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='communityreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityreport',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dangerzone',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dangerzone',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='safetyzone',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='safetyzone',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['user', 'timestamp'], name='accounts_lo_user_id_945aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['session', 'timestamp'], name='accounts_lo_session_3daad2_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['user', 'timestamp'], name='accounts_so_user_id_7dbc1a_idx'),
        ),
    ]
