# Generated by Django 4.2.7 on 2026-04-07 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_trackingsession_expires_at_trackingsession_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingsession',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
